# 6. Hafta 2. Ödev

**1. Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.**

In [24]:
import numpy as np

array = np.array([1, 2, 3, 4, 5], dtype =int)

boyut = array.shape
eleman_sayısı = array.size
boyut_sayısı = array.ndim

print(f"Array: {array}")
print(f"Boyut: {boyut}")
print(f"Eleman sayısı: {eleman_sayısı}")
print(f"Boyut sayısı: {boyut_sayısı}")

Array: [1 2 3 4 5]
Boyut: (5,)
Eleman sayısı: 5
Boyut sayısı: 1


**2. İki ve üç boyutlu arraylar oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.**

In [26]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=int)
array_3d = np.array([[[1,2,3], [4,5,6]],
                      [[7,8,9], [10,11,12]]], dtype=int)

#2 Boyutlu array
print("2 Boyutlu Array:")
print(array_2d)
print("Boyut (ndim):", array_2d.ndim)
print("Eleman sayısı (size):", array_2d.size)
print("Şekil (shape):", array_3d.shape)

print("\n2 Boyutlu Array'den eleman seçme:")
print("array_2d[1, 2]:", array_2d[1, 2])

print("\n2 Boyutlu Array'de dilimleme:")
print("array_2d[1:, 1:]:\n", array_2d[1:, 1:])

#3 Boyutlu array
print("\n3 Boyutlu Array:")
print(array_3d)
print("Boyut (ndim):", array_3d.ndim)
print("Eleman sayısı (size):", array_3d.size)
print("Şekil (shape):", array_3d.shape) 

print("\n3 Boyutlu Array'den eleman seçme:")
print("array_3d[0, 1, 2]:", array_3d[0, 1, 2])

print("\n3 Boyutlu Array'de dilimleme:")
print("array_3d[:, 0, :]:\n", array_3d[:, 0, :])

2 Boyutlu Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Boyut (ndim): 2
Eleman sayısı (size): 9
Şekil (shape): (2, 2, 3)

2 Boyutlu Array'den eleman seçme:
array_2d[1, 2]: 6

2 Boyutlu Array'de dilimleme:
array_2d[1:, 1:]:
 [[5 6]
 [8 9]]

3 Boyutlu Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Boyut (ndim): 3
Eleman sayısı (size): 12
Şekil (shape): (2, 2, 3)

3 Boyutlu Array'den eleman seçme:
array_3d[0, 1, 2]: 6

3 Boyutlu Array'de dilimleme:
array_3d[:, 0, :]:
 [[1 2 3]
 [7 8 9]]


**3. Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arraylar oluşturulur. Arraylar üzerinde indexleme ve dilimleme (slicing) işlemi yapılır.**

In [28]:

array_1d = np.array([10, 20, 30, 40, 50], dtype=int)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]], dtype=int)

# 1 Boyutlu array üzerinde indexleme
print("1 Boyutlu Array'den eleman seçme:")
print("array_1d[2]:", array_1d[2])

# 2 Boyutlu array üzerinde indexleme
print("\n2 Boyutlu Array'den eleman seçme:")
print("array_2d[1, 1]:", array_2d[1, 1]) 

# 3 Boyutlu array üzerinde indexleme
print("\n3 Boyutlu Array'den eleman seçme:")
print("array_3d[1, 0, 2]:", array_3d[1, 0, 2])  

# 1 Boyutlu array üzerinde dilimleme
print("\n1 Boyutlu Array'de dilimleme:")
print("array_1d[1:4]:", array_1d[1:4])  

# 2 Boyutlu array üzerinde dilimleme
print("\n2 Boyutlu Array'de dilimleme:")
print("array_2d[1:, 1:]:\n", array_2d[1:, 1:]) 

# 3 Boyutlu array üzerinde dilimleme
print("\n3 Boyutlu Array'de dilimleme:")
print("array_3d[:, 0, :]:\n", array_3d[:, 0, :])

1 Boyutlu Array'den eleman seçme:
array_1d[2]: 30

2 Boyutlu Array'den eleman seçme:
array_2d[1, 1]: 5

3 Boyutlu Array'den eleman seçme:
array_3d[1, 0, 2]: 9

1 Boyutlu Array'de dilimleme:
array_1d[1:4]: [20 30 40]

2 Boyutlu Array'de dilimleme:
array_2d[1:, 1:]:
 [[5 6]
 [8 9]]

3 Boyutlu Array'de dilimleme:
array_3d[:, 0, :]:
 [[1 2 3]
 [7 8 9]]


**4. Sıfırlardan oluşan ve birden oluşan iki tane iki boyutlu array oluşturulur. Bu arraylar satır ve sütun bazında birleştirilir.**

In [34]:
zeros_array = np.zeros((2, 3), dtype=int)
ones_array = np.ones((2, 3), dtype=int)

# Satır bazında birleştirme (row-wise)
row_concat = np.vstack((zeros_array, ones_array))

# Sütun bazında birleştirme (column-wise)
column_concat = np.hstack((zeros_array, ones_array))

print("Sıfırlardan oluşan array:\n", zeros_array)
print("Birlerden oluşan array:\n", ones_array)

print("\nSatır bazında birleştirme (vstack):\n", row_concat)
print("\nSütun bazında birleştirme (hstack):\n", column_concat)

Sıfırlardan oluşan array:
 [[0 0 0]
 [0 0 0]]
Birlerden oluşan array:
 [[1 1 1]
 [1 1 1]]

Satır bazında birleştirme (vstack):
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirme (hstack):
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
